name: Android builds
on: push

jobs:
  android:
    strategy:
      matrix:
        qt_version: [5.15.2, 6.0.0]
        arch: [android_x86, android_armv7]
        cxx: [g++, clang++]
        include:
          - cxx: g++
            cc: gcc
          - cxx: clang++
            cc: clang

    name: Android (Qt ${{ matrix.qt_version }}, ${{ matrix.arch }}, ${{ matrix.cxx }})
    runs-on: ubuntu-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
        with:
          version: ${{ matrix.qt_version }}

          target: android
          arch: ${{ matrix.arch }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.cc }}
          cxx: ${{ matrix.cxx }}
          build-type: Release
